export const SET_WATCHFORM_FIELD = 'SET_WATCHFORM_FIELD';
export const TOGGLE_WATCHFORM_CHECKBOX = 'TOGGLE_WATCHFORM_CHECKBOX';
export const TOGGLE_MASS_WATCHFORM_CHECKBOX = 'TOGGLE_MASS_WATCHFORM_CHECKBOX';
export const SET_WATCH_IMAGE = 'SET_WATCH_IMAGE';