// WATCH FORM
export const RESET_WATCHFORM = 'RESET_WATCHFORM';
export const SET_WATCHFORM_FIELD = 'SET_WATCHFORM_FIELD';
export const TOGGLE_WATCHFORM_CHECKBOX = 'TOGGLE_WATCHFORM_CHECKBOX';
export const TOGGLE_MASS_WATCHFORM_CHECKBOX = 'TOGGLE_MASS_WATCHFORM_CHECKBOX';
export const SET_WATCH_IMAGES = 'SET_WATCH_IMAGES';
export const SET_REMOVE_IDS = 'SET_REMOVE_IDS';

export const WATCHFORM_START_LOADING = 'WATCHFORM_START_LOADING';
export const WATCHFORM_STOP_LOADING = 'WATCHFORM_STOP_LOADING';

// WATCH LIST
export const SET_WATCH_LIST = 'SET_WATCH_LIST';
export const WATCHLIST_START_FETCH = "WATCHLIST_START_FETCH";