// WATCH FORM
export const RESET_WATCHFORM = 'RESET_WATCHFORM';
export const SET_WATCHFORM_FIELD = 'SET_WATCHFORM_FIELD';
export const TOGGLE_WATCHFORM_CHECKBOX = 'TOGGLE_WATCHFORM_CHECKBOX';
export const TOGGLE_MASS_WATCHFORM_CHECKBOX = 'TOGGLE_MASS_WATCHFORM_CHECKBOX';
export const SET_WATCH_IMAGES = 'SET_WATCH_IMAGES';
export const SET_REMOVE_IDS = 'SET_REMOVE_IDS';
export const SET_IMPORT_IMAGES = 'SET_IMPORT_IMAGES';
export const REMOVE_IMPORT_IMAGE = 'REMOVE_IMPORT_IMAGE';
export const SET_WATCHFORM_ERROR = 'SET_WATCHFORM_ERROR';
export const SET_WATCHFORM_VALID = 'SET_WATCHFORM_VALID';
export const WATCHFORM_SUBMIT_SUCCESS = 'WATCHFORM_SUBMIT_SUCCESS';

export const WATCHFORM_START_LOADING = 'WATCHFORM_START_LOADING';
export const WATCHFORM_STOP_LOADING = 'WATCHFORM_STOP_LOADING';

export const WATCHFORM_START_IMAGE_LOADING = 'WATCHFORM_START_IMAGE_LOADING';
export const WATCHFORM_STOP_IMAGE_LOADING = 'WATCHFORM_STOP_IMAGE_LOADING';


// WATCH LIST
export const SET_WATCH_LIST = 'SET_WATCH_LIST';
export const SET_WATCH_LIST_FILTER = 'SET_WATCH_LIST_FILTER';
export const WATCHLIST_START_FETCH = "WATCHLIST_START_FETCH";

// JEWELRY FORM
export const RESET_JEWELRYFORM = 'RESET_JEWELRYFORM';
export const SET_JEWELRYFORM_FIELD = 'SET_JEWELRYFORM_FIELD';
export const TOGGLE_JEWELRYFORM_CHECKBOX = 'TOGGLE_JEWELRYFORM_CHECKBOX';
export const SET_JEWELRY_IMAGES = 'SET_JEWELRY_IMAGES';
export const SET_JEWELRY_REMOVE_IDS = 'SET_JEWELRY_REMOVE_IDS';
export const SET_JEWELRY_IMPORT_IMAGES = 'SET_JEWELRY_IMPORT_IMAGES';
export const REMOVE_JEWELRY_IMPORT_IMAGE = 'REMOVE_JEWELRY_IMPORT_IMAGE';
export const SET_JEWELRYFORM_VALID = 'SET_JEWELRYFOR_VALID';
export const SET_JEWELRYFORM_ERROR = 'SET_JEWELRYFORM_ERROR';


export const JEWELRYFORM_START_IMAGE_LOADING = 'JEWELRYFORM_START_IMAGE_LOADING';
export const JEWELRYFORM_STOP_IMAGE_LOADING = 'JEWELRYFORM_STOP_IMAGE_LOADING';